### ISSUE TITLE
[don't know]: invalid packet (ctb=2d)

### ISSUE THREAD

**Issue by ZeroChaos-** [mgorny/glep63-check#6]
I got this error on my CI
```
zero@Nu ~ % glep63-check --keyring /usr/share/pentoo/pentoo-keyring.asc                                                                                                                   1 ⨯
gpg: checking the trustdb
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_search failed: Invalid packet
gpg: public key of ultimately trusted key A5DD1427DD11F94A not found
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_search(first) failed: Invalid packet
gpg: validate_key_list failed
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_search_first failed: Invalid packet
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/glep63-check", line 12, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/glep63/cli.py", line 65, in main
    keys.extend(process_gnupg_key(opts.keyring, opts.key_id))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/glep63/gnupg.py", line 124, in process_gnupg_key
    raise subprocess.CalledProcessError(s.returncode,
subprocess.CalledProcessError: Command '['gpg2', '--with-colons', '--list-keys', '--fixed-list-mode', '--no-default-keyring', '--keyring', '/usr/share/pentoo/pentoo-keyring.asc']' returned non-zero exit status 2.
```
But it works properly when used in the same directory
```
zero@naga ~ % cd /usr/share/pentoo                                                                                                                                                        1 ⨯
zero@naga pentoo % glep63-check --keyring pentoo-keyring.asc
zero@naga pentoo % 
```
Please update to work when given a path to the keyring

**Comment by mgorny** [comment]
Could you give me an URL to that keyring?
